### ISSUE TITLE
Drop several duties in the middle to someone else failed

### ISSUE THREAD

**Issue by donjar** [commit-tech/takoyaki#71] opened 2018-05-16 04:00 UTC
e.g. I have duty 10am-2pm and I drop 11am-1pm to my friend. It does not work.

**Comment by indocomsoft** [comment] 2019-03-16 00:52
Can't reproduce. Probably fixed by https://github.com/commit-tech/takoyaki/commit/0a8438a2c8cb310bec292f0b3f61293b232ee92a

**Closed by indocomsoft** 2019-03-16 00:52 UTC
